engines:
  nodesecurity:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  csslint:
    enabled: true

ratings:
  paths:
    - "**.js"
    - "**.css"

exclude_paths:
- node_modules/*
- .vagrant/*
- public/lib/*
